export const SITE = {
  name: "Ome Theophilus",
  tagline: "Developer. AI Builder. Automation Engineer.",
  roles: ["Developer", "AI Builder", "Automation Engineer"],
  location: "Nairobi, Kenya",
  bio: "I build AI-powered systems, automation pipelines, and full-stack applications. From multi-agent orchestrators to mobile apps — I ship products that work.",
  contact: {
    phone: "+254729930288",
    email: "theophydake@gmail.com",
    linkedin: "https://www.linkedin.com/in/theophilus-dale-658190423",
    instagram: "https://www.instagram.com/daletheokrazy",
    github: "https://github.com/Hacktool254",
  },
};

export const PROJECTS = [
  {
    name: "Sentinel Agent",
    slug: "sentinel-agent",
    description: "Multi-agent AI orchestrator powered by AWS Bedrock. Telegram bot interface routing tasks across specialized agents — researcher, content, security, finance, sales — with tool use, memory, and workflow automation.",
    tech: ["TypeScript", "AWS Bedrock", "Telegram", "SQLite", "Node.js"],
    isPrivate: true,
    url: "https://github.com/Hacktool254/sentinel-agent",
    image: "/images/projects/sentinel-agent.png",
  },
  {
    name: "Sentinel Dashboard",
    slug: "sentinel-dashboard",
    description: "NEXUS bento command center — a real-time dashboard for monitoring Sentinel agent activity, usage analytics, kanban tasks, and workflow state. Built with Next.js 15 and Convex.",
    tech: ["Next.js", "Convex", "TypeScript", "Tailwind"],
    isPrivate: true,
    url: "https://github.com/Hacktool254/sentinel-dashboard",
    image: "/images/projects/sentinel-dashboard.png",
  },
  {
    name: "Gravity Claw",
    slug: "Gravity-Claw",
    description: "Autonomous AI coding agent that runs the full development lifecycle — planning, scaffolding, writing, testing, and deploying code without human intervention.",
    tech: ["AI", "Automation", "Node.js"],
    isPrivate: true,
    url: "https://github.com/Hacktool254/Gravity-Claw",
    image: "/images/projects/Gravity-Claw.png",
  },
  {
    name: "Kibandaski",
    slug: "kibandaski",
    description: "Mobile-first street food delivery platform for Nairobi. Three-app Expo monorepo serving customers, merchants, and riders across Nairobi's street food ecosystem.",
    tech: ["React Native", "Expo", "TypeScript", "Node.js"],
    isPrivate: true,
    url: "https://github.com/Hacktool254/kibandaski",
    image: "/images/projects/kibandaski.png",
  },
  {
    name: "Ewala Retail Management",
    slug: "ewala-retail-management",
    description: "Full-featured desktop retail management system for Ewala Hardware. Inventory, POS, invoicing, customer management, and reporting built as an Electron app.",
    tech: ["Electron", "React", "TypeScript", "SQLite"],
    isPrivate: true,
    url: "https://github.com/Hacktool254/ewala-retail-management",
    image: "/images/projects/ewala-retail-management.png",
  },
  {
    name: "Sentinel AI Vulnerability Scanner",
    slug: "Sentinel_AI-Vulnerability-Scanner",
    description: "AI-powered vulnerability scanner combining Nmap and OWASP ZAP with LLM intelligence. Prioritizes vulnerabilities by real exploitability, simulates attack paths, and generates structured remediation guidance.",
    tech: ["Python", "AI/LLM", "Nmap", "OWASP ZAP"],
    isPrivate: false,
    url: "https://github.com/Hacktool254/Sentinel_AI-Vulnerability-Scanner",
    image: "/images/projects/Sentinel_AI-Vulnerability-Scanner.png",
  },
  {
    name: "KrazzyVault",
    slug: "KrazzyVault",
    description: "Secure digital vault application with end-to-end encryption for storing sensitive personal and business assets.",
    tech: ["Encryption", "Security", "Web"],
    isPrivate: false,
    url: "https://github.com/Hacktool254/KrazzyVault",
    image: "/images/projects/KrazzyVault.png",
  },
  {
    name: "Cloak",
    slug: "Cloak",
    description: "Chrome extension providing seamless proxy switching with anti-detect fingerprint hardening, one-click connect, and live session stats.",
    tech: ["Chrome Extension", "JavaScript", "Proxy"],
    isPrivate: false,
    url: "https://github.com/Hacktool254/Cloak",
    image: "/images/projects/Cloak.png",
  },
  {
    name: "Sentinel Hills Agency",
    slug: "sentinalhills",
    description: "Web application for Sentinel Hills — an AI automation agency building custom AI solutions, automation pipelines, and intelligent systems for businesses.",
    tech: ["Next.js", "TypeScript", "Tailwind"],
    isPrivate: false,
    url: "https://github.com/Hacktool254/sentinalhills",
    image: "/images/projects/sentinalhills.png",
  },
  {
    name: "Zenix Electronics Store",
    slug: "zenixecommercestore",
    description: "Full-featured electronics ecommerce store with product catalog, cart, checkout, and admin panel.",
    tech: ["Next.js", "TypeScript", "Tailwind", "Convex"],
    isPrivate: false,
    url: "https://github.com/Hacktool254/zenixecommercestore",
    image: "/images/projects/zenixecommercestore.png",
  },
  {
    name: "Ewala Mobile Companion",
    slug: "ewala-mobile-companion",
    description: "Mobile companion app for Ewala Hardware — Expo React Native app for field staff to access inventory, customer data, and orders on the go.",
    tech: ["React Native", "Expo", "TypeScript"],
    isPrivate: true,
    url: "https://github.com/Hacktool254/ewala-mobile-companion",
    image: "/images/projects/ewala-mobile-companion.png",
  },
  {
    name: "Office Appointment Manager",
    slug: "Office-Appointment-Manager",
    description: "Web application for managing office appointments — booking, scheduling, reminders, and staff calendar management.",
    tech: ["React", "Node.js", "PostgreSQL"],
    isPrivate: true,
    url: "https://github.com/Hacktool254/Office-Appointment-Manager",
    image: "/images/projects/Office-Appointment-Manager.png",
  },
  {
    name: "Bitech",
    slug: "Bitech",
    description: "Personal solo project collection — a monorepo of experimental builds, tools, and prototypes built independently.",
    tech: ["TypeScript", "Various"],
    isPrivate: true,
    url: "https://github.com/Hacktool254/Bitech",
    image: "/images/projects/Bitech.png",
  },
  {
    name: "Krazzy App",
    slug: "krazzy-app",
    description: "Creative mobile application built with React Native — a personal project exploring UI/UX patterns and mobile-first design.",
    tech: ["React Native", "Expo"],
    isPrivate: true,
    url: "https://github.com/Hacktool254/krazzy-app",
    image: "/images/projects/krazzy-app.png",
  },
  {
    name: "Flashtrendy Store",
    slug: "flashtrendy-ecommerce-store",
    description: "Fashion ecommerce store with trending product catalog, dynamic filters, and seamless checkout flow.",
    tech: ["React", "JavaScript", "CSS"],
    isPrivate: false,
    url: "https://github.com/Hacktool254/flashtrendy-ecommerce-store",
    image: "/images/projects/flashtrendy-ecommerce-store.png",
  },
  {
    name: "Perfumes Store",
    slug: "perfumes-ecommerce-store",
    description: "Luxury perfumes ecommerce store with elegant product presentation and streamlined purchase experience.",
    tech: ["React", "JavaScript"],
    isPrivate: false,
    url: "https://github.com/Hacktool254/perfumes-ecommerce-store",
    image: "/images/projects/perfumes-ecommerce-store.png",
  },
];

export const STACK = [
  { category: "Languages", items: ["TypeScript", "JavaScript", "Python"] },
  { category: "Frontend", items: ["Next.js", "React", "Tailwind CSS", "Framer Motion"] },
  { category: "Mobile", items: ["React Native", "Expo"] },
  { category: "Backend", items: ["Node.js", "Express", "Convex"] },
  { category: "AI / ML", items: ["AWS Bedrock", "Anthropic Claude", "LangChain", "OpenAI"] },
  { category: "Databases", items: ["SQLite", "PostgreSQL", "Convex", "MongoDB"] },
  { category: "DevOps", items: ["Docker", "GitHub Actions", "Electron", "Systemd"] },
  { category: "Security", items: ["OWASP", "Nmap", "Penetration Testing", "CTF"] },
];
